# Generated by Django 4.1.5 on 2023-02-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
