# Generated by Django 4.1.5 on 2023-01-20 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userinfos_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('ref_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.PositiveBigIntegerField(default=0)),
                ('total_referral_amount', models.PositiveBigIntegerField(default=0)),
                ('total_amount_deposit', models.PositiveIntegerField(default=0)),
                ('total_amount_withdraw', models.PositiveIntegerField(default=0)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_ass', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfos',
        ),
    ]
