# Generated by Django 4.1.5 on 2023-01-23 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_partner_last_partern_added_alter_partner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='first_partern_added',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_partner_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
