# Generated by Django 4.1.5 on 2023-01-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userinformation_delete_userinfos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='total_referral_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
