# Generated by Django 4.1.5 on 2023-01-21 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userinformation_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='first_son',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_son', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='first_youngest_brother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mentor', to=settings.AUTH_USER_MODEL),
        ),
    ]
