# Generated by Django 4.1.5 on 2023-01-23 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_partner_first_partern_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='total_amount',
            new_name='total_amount_eth',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='total_referral_amount',
            new_name='total_amount_tron',
        ),
        migrations.AddField(
            model_name='user',
            name='total_amount_usdt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_amount_xaf',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_referral_amount_eth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_referral_amount_tron',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_referral_amount_usdt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_referral_amount_xaf',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partner',
            name='first_partern_added',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
