# Generated by Django 4.1.5 on 2023-01-24 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_total_amount_user_total_amount_eth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_amount_bonus_sub',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='partner',
            name='first_partern_added',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_partner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partner',
            name='next_youngest_brother',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
