# Generated by Django 4.1.5 on 2023-01-21 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userinformation_first_son_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='first_son',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_son', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='first_youngest_brother',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
