# Generated by Django 4.1.5 on 2023-01-26 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('DE', 'Deposit'), ('WI', 'Withdraw')], max_length=2)),
                ('amount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('OM', 'Orange Money'), ('MO', 'Mtn Money')], max_length=4)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Prepared', 'Prepared'), ('Cancel', 'Cancel')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
