# Generated by Django 4.1.5 on 2023-02-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('OM', 'Orange Money'), ('MO', 'Mtn Money'), ('TR', 'Tron'), ('US', 'USDT')], max_length=4),
        ),
    ]
